application:
  name: permanent.marker.service

environment:
  name: dev

server:
  port: 8080

spring:
 datasource:
   url: jdbc:mysql://localhost:3306/permanent_marker
   username: root
   password: passw0rd
   driver: com.mysql.cj.jdbc.Driver
 jpa:
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
